name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install rustfmt with nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run formatter
        run: cargo fmt --manifest-path=Cargo.toml --all -- --check
